spring.application.name=java-ecommerce
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.properties.hibernate.default_schema=e_commerce

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true

jwt.secret=${SECRET_KEY}

# ===============================
# CLOUDINARY
# ===============================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}

cloudinary.api-key=${CLOUDINARY_API_KEY}

cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# ===============================
# MULTIPART
# ===============================

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=50MB

# ===============================
# STRIPE
# ===============================

stripe.api.key=${STRIPE_SECRET_KEY}
stripe.currency=${STRIPE_CURRENCY:inr}
stripe.success.url=${STRIPE_SUCCESS_URL:http://localhost:5173/order-success?session_id={CHECKOUT_SESSION_ID}}
stripe.cancel.url=${STRIPE_CANCEL_URL:http://localhost:5173/order-cancel}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}